### PR TITLE
Feature/login register

### PR DESCRIPTION
**Pull request by apollisa**
Added login and register pages to the front, as well as a non-functional home page (available upon logging in).

Try logging in and logging out and try feeding incorrect values to the forms.

### CODE REVIEW

**Comment by Hackatosh** [comment]
First of all : GG, it looks super nice. I especially liked the randomized background for the login page, good work !

**Bugs :**
- When you login upon registration, the history is not pushed to homepage. You're forced to refresh the page to display correctly the homepage.
Step to reproduce : register => login => After hitting "Se connecter", you are logged in but the push doesn't happen
- In _auth-header.ts_, 'Bearer' should be change to 'JWT' to avoid future problems
- In _RegisterPage.tsx_, password confirmation is not working 

**Required changes :**
- If possible, history.push related to authentication should happen only in _authentication.service.ts_ instead of being spread out in components. This whill allow to fully encapsulate the business logic for authentication in one file
- _index.ts_ files should be deleted as they are not needed and bloat the project. You can see in the current code that _NavBar.tsx_ is not exported in _index.ts_ and works perfectly fine.
- _CurrentUser_ should not be part of the state of _Homepage.tsx_ : _CurrentUser_ is a value shared by multiple components and it shouldn't be part of internal state. This should be accessed using directly authenticationService.currentUserValue.
- _bootstrap_ should be installed as a yarn dependency instead of being imported through index.html. The command probably are `yarn add bootstrap --save` and `yarn add @types/bootstrap --dev`, but you need to check them !
- _jquery_ should be deleted from index.html and **never used in the project**. _jquery_ is used to manipulate directly DOM elements and this a bad idea to use it with React.

** Suggested improvements :**
- _config.ts_ should use env variables

**Comment by apollisa** [comment]
Everything is fixed/changed, except this @Raklyon! 
>     * In **_RegisterPage.tsx_**, password confirmation is not working

**Comment by Zizol** [comment]
Thanks for the amazing code you wrote, very smart ! I especially liked how you commented your code, keep up the good work

**Comment by Raklyon** [comment]
Fixed the last details and went through the new features, looks good!

**Pull request merged**
