### PR TITLE
Feature/event search

### PR DESCRIPTION
**Pull request by Zizol**
Here is my Pull Request, please review it with care !

### CODE REVIEW

**Comment by damianib** [comment]
Very lovely cats, 100% would recommend

**Comment by Zizol** [comment]
To make the new funcitonality work :
click on 'Evenements` in the NavBar. You should see three events.
Upon clicking on `Détails` on the event, you should be redirected to the same event : peche à la ligne.

**Comment by Hackatosh** [comment]
**Bugs :**
- On the 2nd card, the button hide the text. This shouldn't happen.
- Potential bug : what happens if there is more than one row of events ? This needs to be tested first
- Details button is still present in the __Evenement__ Class in **__Events.tsx__**
- The picture in the __Evenement__ Class in **__Events.tsx__** is too big

**Required changes :**
- Everything in the code should be in English. Please change the class __Evenement__ to something else
- __Event__ should be a name used for a model, such as __User.tsx__. For component, naming should explicitly hint that it is a component.
- Please, follow the rule "One file = One component" for __.tsx__ files to make code easier to understand and maintain. The class __Events__ and __Evenement__ should be kept in separate files.

** Suggested Improvements 1/2 :**
- A subrouter could hide the events logic from the app-level switch in **__App.tsx__**
- Placeholders should be added for beginning date, ending date and host of every event, at least in __Evenement__ class
- Please note that you can write :
`export class Events React.Component <...,...> {...}` 
instead of:
` class Events React.Component <...,...> {...} 
export { Events }
`

**Suggested Improvements 2/2 : **
This is a long suggestion to obtain more reusable code :
- Make a class __Event__ in the model folder, which represent the data about one event (id, name, description, dates...). Everything obtained from the API should be converted to this model by the layer of the application accessing the API (such as what is done in **__authentication.service.ts__**)
- For something very basic, you then make a component __EventDetails__ which takes an __Event__ as a prop and display every informations about the __Event__ (such as what you are doing in the current __Evenement__ component) and a component __EventsList__ which takes an array of __Event__ and display basic informations about them, and allow to access the __EventDetails__ component for every event displayed

** Suggested Improvements :**

**Comment by Hackatosh** [comment]
And please don't commit **package-lock.json** !

**Comment by Zizol** [comment]
The requested changes have been made, still needs for the *EventList* and the *EventDetails* class to make use of the *Event* class created in the model folder

**Pull request merged**
